permissions:
  contents: write

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  
  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
  # Also run on pushes to main/master branch
  push:
    branches:
      - main
      - master

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake files (both light and dark theme versions)
      - name: Generate Snake Files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: usharma24
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy the files in dist/ folder to the output branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
